version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-aznu
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-aznu
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  gateway:
    image: aznu/booking
    ports:
      - "8090:8090"
    environment:
      KAFKA_SERVER: kafka:9092
      BOOKING_SERVICE_TYPE: gateway
    depends_on:
      - kafka
  visit:
    image: aznu/booking
    environment:
      KAFKA_SERVER: kafka:9092
      BOOKING_SERVICE_TYPE: visit
    depends_on:
      - kafka
  equipment:
    image: aznu/booking
    environment:
      KAFKA_SERVER: kafka:9092
      BOOKING_SERVICE_TYPE: equipment
    depends_on:
      - kafka
  payment:
    image: aznu/booking
    environment:
      KAFKA_SERVER: kafka:9092
      BOOKING_SERVICE_TYPE: payment
    depends_on:
      - kafka
