
package uni.aznu.visit;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2025-01-12T18:06:06.423+01:00
 * Generated source version: 3.3.2
 *
 */
public final class VisitBookingPortType_VisitBookingSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://visit.aznu.uni", "VisitBookingService");

    private VisitBookingPortType_VisitBookingSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VisitBookingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        VisitBookingService ss = new VisitBookingService(wsdlURL, SERVICE_NAME);
        VisitBookingPortType port = ss.getVisitBookingSoapPort();

        {
        System.out.println("Invoking bookVisit...");
        uni.aznu.visit.BookVisitRequest _bookVisit_parameters = null;
        uni.aznu.visit.BookVisitResponse _bookVisit__return = port.bookVisit(_bookVisit_parameters);
        System.out.println("bookVisit.result=" + _bookVisit__return);


        }

        System.exit(0);
    }

}
