package uni.aznu.visit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2025-01-12T18:06:06.561+01:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "VisitBookingService",
                  wsdlLocation = "file:/C:/Users/Karol/Documents/Java%20projects/aznu_old/src/main/resources/visit.wsdl",
                  targetNamespace = "http://visit.aznu.uni")
public class VisitBookingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://visit.aznu.uni", "VisitBookingService");
    public final static QName VisitBookingSoapPort = new QName("http://visit.aznu.uni", "VisitBookingSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Karol/Documents/Java%20projects/aznu_old/src/main/resources/visit.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VisitBookingService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Karol/Documents/Java%20projects/aznu_old/src/main/resources/visit.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VisitBookingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VisitBookingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VisitBookingService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VisitBookingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VisitBookingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VisitBookingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VisitBookingPortType
     */
    @WebEndpoint(name = "VisitBookingSoapPort")
    public VisitBookingPortType getVisitBookingSoapPort() {
        return super.getPort(VisitBookingSoapPort, VisitBookingPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VisitBookingPortType
     */
    @WebEndpoint(name = "VisitBookingSoapPort")
    public VisitBookingPortType getVisitBookingSoapPort(WebServiceFeature... features) {
        return super.getPort(VisitBookingSoapPort, VisitBookingPortType.class, features);
    }

}
