package uni.aznu.visit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2025-01-12T18:06:06.540+01:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://visit.aznu.uni", name = "VisitBookingPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VisitBookingPortType {

    @WebMethod(operationName = "BookVisit")
    @WebResult(name = "BookVisitResponse", targetNamespace = "http://visit.aznu.uni", partName = "parameters")
    public BookVisitResponse bookVisit(

        @WebParam(partName = "parameters", name = "BookVisitRequest", targetNamespace = "http://visit.aznu.uni")
        BookVisitRequest parameters
    );
}
